dist: trusty
language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: ILLUMINATE_VERSION=5.3.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.6.*

# instal our framework version
before_install:
  - composer require "laravel/framework:${ILLUMINATE_VERSION}" --no-update
  - composer require "laravel/laravel:${ILLUMINATE_VERSION}" --no-update
  # composer create-project laravel/laravel

# install dependencies and build
install:
  - composer update --prefer-source --no-interaction

script:
   - composer test
# Disable PSR2 standards testing until we ready to revisit
#  - vendor/bin/phpcs --standard=psr2 src/
#  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

#after_script:
#  - |
#    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
#      wget https://scrutinizer-ci.com/ocular.phar
#      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
#    fi
